(cl:defpackage optimation_msgs-msg
  (:use )
  (:export
   "<TRAJECTORYEXECUTIONACTION>"
   "TRAJECTORYEXECUTIONACTION"
   "<TRAJECTORYEXECUTIONACTIONFEEDBACK>"
   "TRAJECTORYEXECUTIONACTIONFEEDBACK"
   "<TRAJECTORYEXECUTIONACTIONGOAL>"
   "TRAJECTORYEXECUTIONACTIONGOAL"
   "<TRAJECTORYEXECUTIONACTIONRESULT>"
   "TRAJECTORYEXECUTIONACTIONRESULT"
   "<TRAJECTORYEXECUTIONFEEDBACK>"
   "TRAJECTORYEXECUTIONFEEDBACK"
   "<TRAJECTORYEXECUTIONGOAL>"
   "TRAJECTORYEXECUTIONGOAL"
   "<TRAJECTORYEXECUTIONRESULT>"
   "TRAJECTORYEXECUTIONRESULT"
   "<TRAJECTORY_OPTIMATION_MSG>"
   "TRAJECTORY_OPTIMATION_MSG"
  ))

