// Generated by gencpp from file custom_msgs/AddInts.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_ADDINTS_H
#define CUSTOM_MSGS_MESSAGE_ADDINTS_H

#include <ros/service_traits.h>


#include <custom_msgs/AddIntsRequest.h>
#include <custom_msgs/AddIntsResponse.h>


namespace custom_msgs
{

struct AddInts
{

typedef AddIntsRequest Request;
typedef AddIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddInts
} // namespace custom_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::custom_msgs::AddInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::custom_msgs::AddInts&) { return value(); }
};

template<>
struct DataType< ::custom_msgs::AddInts > {
  static const char* value()
  {
    return "custom_msgs/AddInts";
  }

  static const char* value(const ::custom_msgs::AddInts&) { return value(); }
};


// service_traits::MD5Sum< ::custom_msgs::AddIntsRequest> should match 
// service_traits::MD5Sum< ::custom_msgs::AddInts > 
template<>
struct MD5Sum< ::custom_msgs::AddIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msgs::AddInts >::value();
  }
  static const char* value(const ::custom_msgs::AddIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msgs::AddIntsRequest> should match 
// service_traits::DataType< ::custom_msgs::AddInts > 
template<>
struct DataType< ::custom_msgs::AddIntsRequest>
{
  static const char* value()
  {
    return DataType< ::custom_msgs::AddInts >::value();
  }
  static const char* value(const ::custom_msgs::AddIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::custom_msgs::AddIntsResponse> should match 
// service_traits::MD5Sum< ::custom_msgs::AddInts > 
template<>
struct MD5Sum< ::custom_msgs::AddIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msgs::AddInts >::value();
  }
  static const char* value(const ::custom_msgs::AddIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msgs::AddIntsResponse> should match 
// service_traits::DataType< ::custom_msgs::AddInts > 
template<>
struct DataType< ::custom_msgs::AddIntsResponse>
{
  static const char* value()
  {
    return DataType< ::custom_msgs::AddInts >::value();
  }
  static const char* value(const ::custom_msgs::AddIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_ADDINTS_H
