(cl:defpackage optimation_msgs-srv
  (:use )
  (:export
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "TRAJECTORY_OPTIMATION_SERVICE"
   "<TRAJECTORY_OPTIMATION_SERVICE-REQUEST>"
   "TRAJECTORY_OPTIMATION_SERVICE-REQUEST"
   "<TRAJECTORY_OPTIMATION_SERVICE-RESPONSE>"
   "TRAJECTORY_OPTIMATION_SERVICE-RESPONSE"
  ))

